### ISSUE TITLE
Load WP's jQuery instead of including your own version

### ISSUE THREAD

**Issue by mandiwise** [redacademy/music-heals-winter-2016#2]
You don't need to include the jQuery library with your theme because jQuery comes bundled with WP—you simply have to load it by doing this inside of a function that is hooked in with `wp_enqueue_scripts`:

```
wp_enqueue_script( 'jquery' );
```

In fact, by naming your version of jQuery `jquery`, you're actually creating a potential script conflict.

Please Google "wordpress load jquery the right way" if you're unsure of how to fix this.

**Comment by LemuelReyes** [comment]
Removed local version of jquery library and now only uses wp_enqueue_script( 'jquery' );
