### ISSUE TITLE
No need to escape slashes in a string

### ISSUE THREAD

**Issue by mandiwise** [redacademy/music-heals-winter-2016#4]
On lines 14 and 16 of `content-home.php` you have escaped slashes in a string—these are not needed.

Also, it would be more appropriate to format this line:

```
<img src="<?php echo get_template_directory_uri() . '/assets\/Hamburger menu-01' ?>.svg" alt="Hamburger Menu"/>
```

Like this:

```
<img src="<?php echo get_template_directory_uri(); ?>/assets/Hamburger menu-01.svg" alt="Hamburger Menu" />
```

And you shouldn't have any whitespace in your image names!

**Comment by tg41991** [comment]
Making these changes has resolved the problem of the icons not displaying when viewed in Firefox, however now the icons will not display on the staging site.
