### ISSUE TITLE
Use home_url() function

### ISSUE THREAD

**Issue by mandiwise** [redacademy/music-heals-winter-2016#5]
It's more appropriate to use the `home_url()` or `site_url()` functions than `bloginfo('url')` according to WP theming standards (see `content-home.php`).

Please review the documentation in the Codex for these functions, and replace throughout your theme:

https://codex.wordpress.org/Function_Reference/home_url

https://codex.wordpress.org/Function_Reference/site_url

**Comment by LemuelReyes** [comment]
bloginfo('url') is now replaced with home_url()
