### ISSUE TITLE
Consider whether template partials are necessary

### ISSUE THREAD

**Issue by mandiwise** [redacademy/music-heals-winter-2016#6]
Abstracting code away into reusable partials (stored in the `template-parts` dir) is a good idea, but only necessary if you actually need to re-use those template somewhere.

For example, the `content-home.php` file will not be re-used anywhere else on the site...do you need a partial for this, or could you just include the mark-up directly in your `front-page.php` template?

**Comment by LemuelReyes** [comment]
Partials that weren't meant to be reused have been deleted. They are now in their respective templates.
